root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  log = "tmp/build-errors.log"
  full_bin = "dlv exec ./tmp/main --headless --listen=:2345 --api-version=2 --accept-multiclient"

[watch]
  includes = [
    "cmd",
    "internal",
    "pkg",
    "views",
    "nginx",
    ".env",
    "docker-compose.yml",
    "go.mod",
    "go.sum",
    "crt"
  ]
  excludes = [
    "tmp",
    "data.db"
  ]

[log]
  level = "debug"
